services:
  watcher:
    image: watcher:v0.1.0
    container_name: my-watcher
    restart: unless-stopped
    environment:
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
      - SSH_KNOWN_HOSTS=/home/appuser/.ssh/known_hosts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.yaml:/home/appuser/config.yaml:ro
      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
      - ${HOME}/test/cd:/home/stk/test/cd
      - ./known_hosts:/home/appuser/.ssh/known_hosts
      - state_volume:/etc/watcher/
    ports:
      - "8080:8080"

volumes:
  state_volume:

